version: '3.9'

services:
  # Container untuk Database (PostgreSQL)
  db:
    image: postgres:15
    container_name: moodle-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: moodleuser
      POSTGRES_PASSWORD: yourstrongpassword
      POSTGRES_DB: moodledb
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - moodle-net

  # Container untuk Web Server (Apache + PHP)
  web:
        build: .
        container_name: moodle-web
        restart: unless-stopped
        ports:
          - "8081:80"
        depends_on:
          - db
        volumes:
          - ./moodle:/var/www/html
          - ./moodledata:/var/www/moodledata
          - ./apache-moodle.conf:/etc/apache2/sites-available/000-default.conf
          - ./moodle-php.ini:/usr/local/etc/php/conf.d/moodle-settings.ini
        networks:
          - moodle-net

networks:
  moodle-net:
    driver: bridge